# Setup
title:        Demo page
tagline:      
baseurl:      ""
paginate:     1
locale:       "en"
# A responsive theme for your project on GitHub Pages
# About/contact
author:
  name:       Liang Wan
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
