# Setup
title:        Cross Domain Optimization for Speech Enhancement: Parallel or Cascade? 
tagline:      
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Liang Wan
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
